# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf3d384deaca66cbf4e0ea69eed84e3d8131ec42df6a496dd833fcf94bae772a1b4229774ee27a2f01bbf26a1422d32ae0e17836317d3ce2ffa8ca93e567934f

test:
  secret_key_base: 964f5c4de8b38dcc4a360d26ff0670726cd35683091628e48029ed60d5b1d04c844f73e21f2f3a9108be72d201610910a748454f9ef0146adb63239a2b9ba978

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
